name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# GitHub Pages用の権限設定
permissions:
  contents: read
  pages: write
  id-token: write

# 同時実行の制御
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # ビルドジョブ
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Create docs directory for GitHub Pages
      run: |
        # GitHub Pages用のディレクトリ作成
        mkdir -p docs

        # フロントエンドファイルをdocsにコピー
        cp -r frontend/* docs/

        # 開発用ドキュメントは除外（混同を避ける）
        rm -rf docs/docs 2>/dev/null || true

        # GitHub Pages用の設定ファイル作成
        echo "FC-CRM System - GitHub Pages" > docs/README.md

        # 本番用設定に更新
        # API URLをコメントアウトして開発モード判定でfallback
        sed -i 's|BASE_URL: '\''https://your-domain.com/api'\''|// BASE_URL: '\''https://your-domain.com/api'\'' // Will use development mode|g' docs/js/config.js

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs

  # デプロイジョブ
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4